task:
  name: "x86_64 Linux  [GOAL: install]  [focal]  [Using ./ci/ system]"
  container:
    image: ubuntu:focal
    cpu: 8
    memory: 8G
  timeout_in: 60m
  env:
    MAKEJOBS: "-j9"
    DANGER_RUN_CI_ON_HOST: "1"
    CCACHE_SIZE: "200M"
    CCACHE_DIR: "/tmp/ccache_dir"
  ccache_cache:
    folder: "/tmp/ccache_dir"
  depends_built_cache:
    folder: "/tmp/cirrus-ci-build/depends/built"
  ci_script:
    - ./ci/test_run_all.sh
